### ISSUE TITLE
travis: doctree build fails

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-jsonschemas#59] opened 2017-06-02 15:48 UTC
**Problem:**
Deploy works but there is an error in the logs:
```
running upload_docs
Upload_docs command is deprecated. Use RTD instead.
creating /home/travis/build/inveniosoftware/invenio-jsonschemas/docs/_build/doctrees
Traceback (most recent call last):
  File "setup.py", line 119, in <module>
    'Development Status :: 4 - Beta',
  File "/opt/python/2.7.9/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/python/2.7.9/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/python/2.7.9/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/python/2.7.9/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/command/upload_docs.py", line 65, in finalize_options
    self.target_dir = build_sphinx.builder_target_dir
  File "/opt/python/2.7.9/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: builder_target_dir
```
See https://travis-ci.org/inveniosoftware/invenio-jsonschemas/jobs/238801698

**Comment by switowski** [comment] 2017-10-10 15:25
Hmm, I'm having problems with reproducing this one.
The error didn't occur on the `v1.0.0a5` release (https://travis-ci.org/inveniosoftware/invenio-jsonschemas/jobs/260515385) and I'm also trying to create a dummy PR to see if the error will show up (https://travis-ci.org/switowski/invenio-jsonschemas/builds/286083760) but the error is not there (maybe because the error happened when a deploy to PyPI was prepared?).
I searched also for this `upload_docs` function but I think it's some internal stuff of travis when it deploys to PyPI, so maybe it was something that was fixed already?
@nharraud do you have any other idea how I can try to reproduce the error?

**Comment by lnielsen** [comment] 2017-10-11 06:28
Then we can likely close this one, since pythonhosted (which upload_docs uploads to) is being shutdown

**Comment by switowski** [comment] 2017-10-11 06:31
I'm closing it. If anyone encounters the problem in the future and finds a way to reproduce, we can reopen it.

**Closed as completed by switowski** 2017-10-11 06:31 UTC
Labels: Type: bug, Status: ready for work
